import { dayFivePartOne, dayFivePartTwo } from "./dayFive";
import { dayFourPartOne, dayFourPartTwo } from "./dayFour";
import { dayOnePartOne, dayOnePartTwo } from "./dayOne";
import { daySevenPartOne } from "./daySeven";
import { daySixPartOne, daySixPartTwo } from "./daySix";
import { dayThreePartOne, dayThreePartTwo } from "./dayThree";
import { dayTwoPartOne, dayTwoPartTwo } from "./dayTwo";

// dayOnePartOne();
// dayOnePartTwo();
// dayTwoPartOne();
// dayTwoPartTwo();
// dayThreePartOne();
// dayThreePartTwo();
// dayFourPartOne();
// dayFourPartTwo();
// dayFivePartOne();
// dayFivePartTwo();
// daySixPartOne();
// daySixPartTwo();
daySevenPartOne();
