import { dayFivePartOne, dayFivePartTwo } from "./5dayFive/dayFive";
import { dayFourPartOne, dayFourPartTwo } from "./4dayFour/dayFour";
import { dayOnePartOne, dayOnePartTwo } from "./1dayOne/dayOne";
import { daySevenPartOne, daySevenPartTwo } from "./7daySeven/daySeven";
import { daySixPartOne, daySixPartTwo } from "./6daySix/daySix";
import { dayThreePartOne, dayThreePartTwo } from "./3dayThree/dayThree";
import { dayTwoPartOne, dayTwoPartTwo } from "./2dayTwo/dayTwo";
import { dayEightPartOne, dayEightPartTwo } from "./8dayEight/dayEight";

// dayOnePartOne();
// dayOnePartTwo();
// dayTwoPartOne();
// dayTwoPartTwo();
// dayThreePartOne();
// dayThreePartTwo();
// dayFourPartOne();
// dayFourPartTwo();
// dayFivePartOne();
// dayFivePartTwo();
// daySixPartOne();
// daySixPartTwo();
// daySevenPartOne();
// daySevenPartTwo();
// dayEightPartOne();
dayEightPartTwo();